---
title: "Combined Clustering Analysis"
params:
  num_dimensions_use_anchor: 30
  num_dimensions_use_pca: 30
  resolution: 0.2
  seurat_RDS: NULL
  input_file: 
  label_name: Sample
  labels: NULL
  out_dir: rmarkdown/
output:
  html_document:
    df_print: paged
---

```{r}
print(params)
parameters <- params

parameters[["seurat_out_path"]] <- paste0(
    parameters[["out_dir"]],
    "/combined_seurat.RDS")

parameters[["cache_mode"]] <- file.exists(parameters[["seurat_out_path"]] )

if(parameters[["cache_mode"]]) warning("Running in cache mode, make sure that is what you want")

```

```{r}
library(dplyr)
require(edgeR)
library(tidyverse)
library(Seurat)
library(sctree)
library(purrr)

set.seed(42)
```

```{r readingdata}
if (!parameters[["cache_mode"]]) {
  alldata <- lapply(parameters[["seurat_RDS"]], readRDS)

  add_labels <- function(seurat.obj, label, label_name) {
    seurat.obj[[label_name]] <- label
    return(seurat.obj)
  }
  
  alldata <- purrr::map2(
    alldata, 
    parameters[["labels"]],
    add_labels, 
    parameters[["label_name"]])
  
  saveRDS(
    alldata,
    file = paste0(
      parameters[["out_dir"]],
      "/list_seurat.RDS"))
} else {
  alldata <- readRDS(paste0(
      parameters[["out_dir"]],
      "/list_seurat.RDS"))
}

```

```{r anchors}
if (!parameters[["cache_mode"]]) {
  anchors <- FindIntegrationAnchors(
    object.list = alldata, 
    dims = 1:parameters[["num_dimensions_use_anchor"]])

  combined_seurat_obj <- IntegrateData(
    anchorset = anchors,
    dims = 1:parameters[["num_dimensions_use_anchor"]])
  
  DefaultAssay(combined_seurat_obj) <- "integrated"
} else {
  combined_seurat_obj <- readRDS(parameters[["seurat_out_path"]])
}

```


```{r scaling}
# Run the standard workflow for visualization and clustering
combined_seurat_obj <- ScaleData(
  combined_seurat_obj,
  vars.to.regress = c("nCount_RNA", "percent.mt"))

combined_seurat_obj <- RunPCA(
  combined_seurat_obj,
  npcs = 30, 
  verbose = FALSE)

ElbowPlot(combined_seurat_obj)
```

```{r umap}
combined_seurat_obj <- RunUMAP(
    combined_seurat_obj, reduction = "pca", 
    dims = 1:parameters[["num_dimensions_use_pca"]],
    n.epochs = 500, min.dist = 0.4)

combined_seurat_obj <- FindNeighbors(
  combined_seurat_obj, 
  reduction = "pca", 
  dims = 1:parameters[["num_dimensions_use_pca"]])

combined_seurat_obj <- FindClusters(
  combined_seurat_obj, 
  resolution = parameters[["resolution"]])
```


```{r saving_obj}

if (!parameters[["cache_mode"]] ) {
  message("Saving Object")
  saveRDS(
    combined_seurat_obj,
    file = parameters[["seurat_out_path"]])
}



# Visualization
p1 <- DimPlot(
  combined_seurat_obj, 
  reduction = "pca",
  group.by = parameters[["label_name"]])
p2 <- DimPlot(
  combined_seurat_obj, 
  reduction = "pca",
  group.by = parameters[["label_name"]],
  dims = c(1,3))
p3 <- DimPlot(
  combined_seurat_obj,
  reduction = "pca", 
  label = TRUE)
p1
p2
p3

# Visualization
p1 <- DimPlot(
  combined_seurat_obj, 
  reduction = "umap",
  group.by = parameters[["label_name"]])
p2 <- DimPlot(
  combined_seurat_obj,
  reduction = "umap", 
  label = TRUE)
p3 <- DimPlot(
  combined_seurat_obj, 
  reduction = "umap",
  group.by = "orig.ident")
p1
p2
p3

```

```{r counting}
g <- DimPlot(
  combined_seurat_obj,
  reduction = "umap",
  split.by = parameters[["label_name"]]) + theme_bw()
g

count_table <- as.data.frame(
    table(ident = combined_seurat_obj@active.ident,
          label = combined_seurat_obj@meta.data[[parameters[["label_name"]]]])) 


count_table %>%
  ggplot(
    aes_string(
      x = "ident", 
      fill = "label",
      y = "Freq")) + 
  ggplot2::geom_col(
    position = position_dodge(),
    width = 0.8)  + 
  theme_bw() + 
  ggtitle("Number of cells in each cluster")


count_table %>%
  group_by(label) %>%
  mutate(Freq_pct = Freq/sum(Freq))  %>%
  ggplot(
    aes_string(
      x = "ident", 
      fill = "label",
      y = "Freq_pct")) + 
  ggplot2::geom_col(
    position = position_dodge(), 
    width = 0.8) + 
  theme_bw() + 
  ggtitle("Percentage of cells in each cluster")
```

```{r markers}
markers_cache_file <- paste0(
    parameters[["out_dir"]],
    "/list_markers_seurat_combined.RDS")

if (file.exists(markers_cache_file)) {
  warning("Reading Marker List from cache, make sure you want that ...")
  allmarkers <- readRDS(markers_cache_file)
} else {
  allmarkers <- lapply(
    sort(unique(combined_seurat_obj@active.ident)), 
    (function(x) {
        try({
          foo <- FindConservedMarkers(
            combined_seurat_obj,
            ident.1 = x,
            grouping.var = parameters[["label_name"]],
            verbose = TRUE,
            assay = "RNA",
            logfc.threshold = 1,
            min.pct = 0.3, min.diff.pct = 0.1)
        return(foo)
        })
      }))

  saveRDS(
    allmarkers,
    file = markers_cache_file)
}

names(allmarkers) <- sort(unique(combined_seurat_obj@active.ident))
passed_markers <- allmarkers[sapply(allmarkers, is.data.frame)]
failed_markers <- allmarkers[!sapply(allmarkers, is.data.frame)]

if (length(failed_markers) > 0) {
  warning(paste0("Markers for clusters: ",
       paste(names(failed_markers), 
             collapse = ", "),
       " Failed, a lower cutoff could be attempted"))
}

top_markers <- lapply(passed_markers, function(x) {rownames(head(x, 4))})
```

```{r fig.height=5, fig.width=14}
markers.to.plot <- unique(unlist(top_markers))

DotPlot(combined_seurat_obj,
        features = rev(markers.to.plot), 
        cols = c("blue", "red")) + 
    RotatedAxis()
```

```{r fig.height=6, fig.width=14}
markers_cache_file <- paste0(
    parameters[["out_dir"]],
    "/list_markers_sctree_combined.RDS")

if (file.exists(markers_cache_file)) {
  warning("Reading Marker (sctree) List from cache, make sure you want that ...")
  foo <- readRDS(markers_cache_file)
} else {
  foo <- sctree::FindAllMarkers_ranger.Seurat(
    combined_seurat_obj,
    VariableFeatures(combined_seurat_obj))

  saveRDS(
    foo,
    file = markers_cache_file)
}


head(foo)
foo %>% 
    group_by(cluster) %>% 
    dplyr::top_n(n = 4, wt = importance) %>% 
    .$gene %>% unique() %>%
  DotPlot(combined_seurat_obj, features = ., 
          cols = c("blue", "red")) + Seurat::RotatedAxis()
```

```{r eval=TRUE}
c("CD8A","CD9",
  "CD83","CD74","MZB1",
  "KIT","KLRD1") %>%
  DotPlot(combined_seurat_obj,
        features = ., 
        cols = c("blue", "red")) + 
    RotatedAxis()
```

```{r eval=TRUE, fig.height=15, fig.width=20, include=FALSE}

c("CD3G","CD4","CD8A",
  "CD9","CD79A","CD83",
  "CD74","CD247","ITGAX",
  "MZB1","KIT","KLRD1") %>%
    VlnPlot(combined_seurat_obj,
        features = ., log = FALSE, adjust = 0.2 , ncol = 3)

```



```{r}
g <- DimPlot(combined_seurat_obj, split.by = parameters[["label_name"]]) + theme_bw()
g
ggsave(
  g, filename = paste0(
    parameters[["out_dir"]],
    "/combined_umap.png"), 
  width = 8, height = 4)
```

# Naiive Clustering

```{r}
# V1
# my_counts <- combined_seurat_obj@assays$RNA@counts

# V2
my_counts <- map2(alldata, seq_along(alldata), function(seur_obj, obj_num) {
    my_matrix <- seur_obj@assays$RNA@counts
    colnames(my_matrix) <- paste0(colnames(my_matrix), "_", obj_num)
    return(my_matrix)
})

#merge_matrix <- function(x, y) {
#    cbind(x, y[match(rownames(x), rownames(y)),])
#}
#my_counts2 <- merge_matrix(my_counts[[1]],my_counts[[2]])

row_names_match <- all(mapply(
    (function(x, y) all(rownames(x) == rownames(y))),
    x = my_counts, 
    MoreArgs = list(y = my_counts[[1]])))

stopifnot(row_names_match)
my_counts <- do.call(cbind, my_counts)


Naiive_Seurat <- CreateSeuratObject(my_counts, project = "Naive_clustering")

Naiive_Seurat[["orig.ident"]] <- plyr::mapvalues(
    rownames(Naiive_Seurat@meta.data),
    from = rownames(combined_seurat_obj@meta.data),
    to = combined_seurat_obj@meta.data$orig.ident) 

Naiive_Seurat[[ parameters[["label_name"]] ]] <- plyr::mapvalues(
    rownames(Naiive_Seurat@meta.data),
    from = rownames(combined_seurat_obj@meta.data),
    to = combined_seurat_obj@meta.data[[ parameters[["label_name"]] ]]) 

Naiive_Seurat[[ "Assigned_Cluster_CCA" ]] <- plyr::mapvalues(
    rownames(Naiive_Seurat@meta.data),
    from = rownames(combined_seurat_obj@meta.data),
    to = combined_seurat_obj@active.ident) 


Naiive_Seurat <- FindVariableFeatures(Naiive_Seurat, "RNA", nfeatures = 3000)

Naiive_Seurat <- ScaleData(
    Naiive_Seurat,
    vars.to.regress = c("nCount_RNA", "percent.mt"))

Naiive_Seurat <- RunPCA(
    Naiive_Seurat,
    npcs = 30, 
    verbose = FALSE)

ElbowPlot(Naiive_Seurat)
Naiive_Seurat <- RunUMAP(
    Naiive_Seurat, reduction = "pca", 
    dims = 1:parameters[["num_dimensions_use_pca"]],
    n.epochs = 500, min.dist = 0.4)

Naiive_Seurat <- FindNeighbors(
    Naiive_Seurat, 
    reduction = "pca", 
    dims = 1:parameters[["num_dimensions_use_pca"]])

Naiive_Seurat <- FindClusters(
    Naiive_Seurat, 
    resolution = parameters[["resolution"]])


# Visualization
p1 <- DimPlot(
    Naiive_Seurat, 
    reduction = "pca",
    group.by = parameters[["label_name"]])
p2 <- DimPlot(
    Naiive_Seurat, 
    reduction = "pca",
    group.by = "Assigned_Cluster_CCA", split.by = "orig.ident")

DimPlot(
    Naiive_Seurat, 
    reduction = "pca",
    group.by = "Assigned_Cluster_CCA", split.by = "orig.ident", dims = c(1,3))


p3 <- DimPlot(
    Naiive_Seurat,
    reduction = "pca", 
    label = TRUE)
p4 <- DimPlot(
    Naiive_Seurat,
    reduction = "pca", 
    group.by = "Assigned_Cluster_CCA",
    label = TRUE,
    dims = c(1,3))
p1
p2
p3
p4



# Visualization
p1 <- DimPlot(
    Naiive_Seurat, 
    reduction = "umap",
    group.by = parameters[["label_name"]])
p2 <- DimPlot(
    Naiive_Seurat,
    reduction = "umap", 
    label = TRUE)
p3 <- DimPlot(
    Naiive_Seurat, 
    reduction = "umap",
    group.by = "orig.ident")
p4 <- DimPlot(
    Naiive_Seurat,
    reduction = "umap", 
    group.by = "Assigned_Cluster_CCA",
    label = TRUE)
p1
p2
p3
p4

```


```{r}
sessionInfo()
```
